In [1]:
import pandas as pd
from scrapers import scrap_reviews_trustpilot
from scrapers.analysis.analysis_tools import avg_rating_month_data, n_rating_month, get_analysis

In [2]:
url = "https://www.trustpilot.com/review/tripmate.com"

In [3]:
res = scrap_reviews_trustpilot(url)

Starting to scrap...
Done with https://www.trustpilot.com/review/tripmate.com
Done 1/23 (4%)
Done with https://www.trustpilot.com/review/tripmate.com?page=2
Done 2/23 (8%)
Done with https://www.trustpilot.com/review/tripmate.com?page=3
Done 3/23 (13%)
Done with https://www.trustpilot.com/review/tripmate.com?page=4
Done 4/23 (17%)
Done with https://www.trustpilot.com/review/tripmate.com?page=5
Done 5/23 (21%)
Done with https://www.trustpilot.com/review/tripmate.com?page=6
Done 6/23 (26%)
Done with https://www.trustpilot.com/review/tripmate.com?page=7
Done 7/23 (30%)
Done with https://www.trustpilot.com/review/tripmate.com?page=8
Done 8/23 (34%)
Done with https://www.trustpilot.com/review/tripmate.com?page=9
Done 9/23 (39%)
Done with https://www.trustpilot.com/review/tripmate.com?page=10
Done 10/23 (43%)
Done with https://www.trustpilot.com/review/tripmate.com?page=11
Done 11/23 (47%)
Done with https://www.trustpilot.com/review/tripmate.com?page=12
Done 12/23 (52%)
Done with https://www.trustpilot.com/review/tripmate.com?page=13
Done 13/23 (56%)
Done with https://www.trustpilot.com/review/tripmate.com?page=14
Done 14/23 (60%)
Done with https://www.trustpilot.com/review/tripmate.com?page=15
Done 15/23 (65%)
Done with https://www.trustpilot.com/review/tripmate.com?page=16
Done 16/23 (69%)
Done with https://www.trustpilot.com/review/tripmate.com?page=17
Done 17/23 (73%)
Done with https://www.trustpilot.com/review/tripmate.com?page=18
Done 18/23 (78%)
Done with https://www.trustpilot.com/review/tripmate.com?page=19
Done 19/23 (82%)
Done with https://www.trustpilot.com/review/tripmate.com?page=20
Done 20/23 (86%)
Done with https://www.trustpilot.com/review/tripmate.com?page=21
Done 21/23 (91%)
Done with https://www.trustpilot.com/review/tripmate.com?page=22
Done 22/23 (95%)

In [4]:
reviews = res["reviews"]
df = pd.DataFrame(reviews)
df.head()

,company,review_id,rating_star,date,title,review,customer_location,n_reviews_customer_hide,is_verified,verification_source_hide,review_source_hide,verification_level_hide,reply_content_hide,rating_star_cleaned_hide,n_reviews_customer_cleaned_hide,date_year_month_hide,text_cleaned_hide,page
0,Trip Mate,6063d8d2f85d7508703f19e2,1 star: Bad,2021-03-31T02:05:06+00:00,Waiting and Hoping My Claim Comes Thru,Boy am I scared now. I've had a Tripmate clai...,US,2 reviews,False,,,,Thank you for reaching out. The claims process...,1,2,2021-03,waiting and hoping my claim comes thru boy am ...,1
1,Trip Mate,605b2b17f85d7507e41f7c1c,5 stars: Excellent,2021-03-24T12:05:43+00:00,A movement security plan is a bundle of…,A movement security plan is a bundle of advant...,NA,1 review,False,,,,,5,1,2021-03,a movement security plan is a bundle of… a mov...,1
2,Trip Mate,6058ba22f85d750870304bb2,4 stars: Great,2021-03-22T15:39:14+00:00,My claim went through with no issues,My claim went through with no issues. Just fi...,US,1 review,False,,,,,4,1,2021-03,my claim went through with no issues my claim ...,1
3,Trip Mate,60554ff3f85d750bf4f9b800,1 star: Bad,2021-03-20T01:29:23+00:00,Bounced Check from claim payout,I am beyond words in dealing with this company...,US,1 review,False,,,,We're sorry to hear about the circumstances su...,1,1,2021-03,bounced check from claim payout i am beyond wo...,1
4,Trip Mate,604da480f85d75064c40daee,5 stars: Excellent,2021-03-14T05:52:00+00:00,A five star for this caused they love…,A five star for this caused they love and resp...,PH,3 reviews,False,,,,,5,3,2021-03,a five star for this caused they love… a five ...,1

In [5]:
avg_rating_month_data(df)

   date_year_month_hide                   level_1         0
0            2018-02-01  rating_star_cleaned_hide  2.000000
1            2018-03-01  rating_star_cleaned_hide  0.000000
2            2018-04-01  rating_star_cleaned_hide  0.000000
3            2018-05-01  rating_star_cleaned_hide  0.000000
4            2018-06-01  rating_star_cleaned_hide  0.000000
..                  ...                       ...       ...
33           2020-11-01       avg_rating_uptodate  3.350365
34           2020-12-01       avg_rating_uptodate  3.341346
35           2021-01-01       avg_rating_uptodate  3.310588
36           2021-02-01       avg_rating_uptodate  3.310748
37           2021-03-01       avg_rating_uptodate  3.309469

[76 rows x 3 columns]

In [6]:
n_rating_month(df)

    date_year_month_hide  rating_star_cleaned_hide  text_cleaned_hide
0             2018-02-01                         1                  0
1             2018-03-01                         1                  0
2             2018-04-01                         1                  0
3             2018-05-01                         1                  0
4             2018-06-01                         1                  0
..                   ...                       ...                ...
185           2020-11-01                         5                  9
186           2020-12-01                         5                  2
187           2021-01-01                         5                  1
188           2021-02-01                         5                  1
189           2021-03-01                         5                  2

[190 rows x 3 columns]

In [11]:
??get_analysis

In [7]:
dict_analysis = get_analysis(df)

In [8]:
dict_analysis['Reviews']

,company,review_id,rating_star,date,title,review,customer_location,n_reviews_customer_hide,is_verified,verification_source_hide,review_source_hide,verification_level_hide,reply_content_hide,rating_star_cleaned_hide,n_reviews_customer_cleaned_hide,date_year_month_hide,text_cleaned_hide,page
0,Trip Mate,6063d8d2f85d7508703f19e2,1 star: Bad,2021-03-31T02:05:06+00:00,Waiting and Hoping My Claim Comes Thru,Boy am I scared now. I've had a Tripmate clai...,US,2 reviews,False,,,,Thank you for reaching out. The claims process...,1,2,2021-03,waiting and hoping my claim comes thru boy am ...,1
1,Trip Mate,605b2b17f85d7507e41f7c1c,5 stars: Excellent,2021-03-24T12:05:43+00:00,A movement security plan is a bundle of…,A movement security plan is a bundle of advant...,NA,1 review,False,,,,,5,1,2021-03,a movement security plan is a bundle of… a mov...,1
2,Trip Mate,6058ba22f85d750870304bb2,4 stars: Great,2021-03-22T15:39:14+00:00,My claim went through with no issues,My claim went through with no issues. Just fi...,US,1 review,False,,,,,4,1,2021-03,my claim went through with no issues my claim ...,1
3,Trip Mate,60554ff3f85d750bf4f9b800,1 star: Bad,2021-03-20T01:29:23+00:00,Bounced Check from claim payout,I am beyond words in dealing with this company...,US,1 review,False,,,,We're sorry to hear about the circumstances su...,1,1,2021-03,bounced check from claim payout i am beyond wo...,1
4,Trip Mate,604da480f85d75064c40daee,5 stars: Excellent,2021-03-14T05:52:00+00:00,A five star for this caused they love…,A five star for this caused they love and resp...,PH,3 reviews,False,,,,,5,3,2021-03,a five star for this caused they love… a five ...,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
428,Trip Mate,5bce2c449d378002d88d7496,5 stars: Excellent,2018-10-22T20:00:04Z,Missed connection,My fiancé booked a trip to Italy… And due to a...,,1 review,False,,,,"Thanks for the kind words, Ed! So sorry to hea...",5,1,2018-10,missed connection my fiancé booked a trip to i...,22
429,Trip Mate,5bc0ca929d37800998565017,3 stars: Average,2018-10-12T16:23:46Z,My overall satisfaction with Tripmate…,My overall satisfaction with Tripmate was quit...,,2 reviews,False,,,,"Hi Patrick, Thank you for sharing your kind wo...",3,2,2018-10,my overall satisfaction with tripmate… my over...,22
430,Trip Mate,5bb7cc529d37800778c40fa2,5 stars: Excellent,2018-10-05T20:40:50Z,I had a very stressful and frustrating situati...,I had a very stressful and frustrating situati...,,2 reviews,False,,,,"Hi Teri, Thank you so much for sharing your ex...",5,2,2018-10,i had a very stressful and frustrating situati...,22
431,Trip Mate,5b7de1b314b7d8018cff096e,5 stars: Excellent,2018-08-22T22:20:35Z,Incredible customer service,Incredible customer service. Prompt e-mail res...,,1 review,False,,,,"Thanks, Jessica! We're so happy to hear this. ...",5,1,2018-08,incredible customer service incredible custome...,22
432,Trip Mate,5a8b24f4d27b0a052073fb54,2 stars: Poor,2018-02-19T19:26:44Z,The worst company I have EVER dealt with in th...,The worst company I have EVER come across in t...,,8 reviews,False,,,,,2,8,2018-02,the worst company i have ever dealt with in th...,22

In [9]:
dict_analysis['Average Rating']

   date_year_month_hide                   level_1         0
0            2018-02-01  rating_star_cleaned_hide  2.000000
1            2018-03-01  rating_star_cleaned_hide  0.000000
2            2018-04-01  rating_star_cleaned_hide  0.000000
3            2018-05-01  rating_star_cleaned_hide  0.000000
4            2018-06-01  rating_star_cleaned_hide  0.000000
..                  ...                       ...       ...
33           2020-11-01       avg_rating_uptodate  3.350365
34           2020-12-01       avg_rating_uptodate  3.341346
35           2021-01-01       avg_rating_uptodate  3.310588
36           2021-02-01       avg_rating_uptodate  3.310748
37           2021-03-01       avg_rating_uptodate  3.309469

[76 rows x 3 columns]

In [10]:
dict_analysis['N Rating']

    date_year_month_hide  rating_star_cleaned_hide  text_cleaned_hide
0             2018-02-01                         1                  0
1             2018-03-01                         1                  0
2             2018-04-01                         1                  0
3             2018-05-01                         1                  0
4             2018-06-01                         1                  0
..                   ...                       ...                ...
185           2020-11-01                         5                  9
186           2020-12-01                         5                  2
187           2021-01-01                         5                  1
188           2021-02-01                         5                  1
189           2021-03-01                         5                  2

[190 rows x 3 columns]

In [12]:
dict_analysis = get_analysis(df, "trustpilot_tripmate.xlsx")

trustpilot_tripmate.xlsx saved